site_name: MAGELLAN 9 DB
site_author: STÜBER SYSTEMS GmbH
site_description: Dokumentation der MAGELLAN 9 Datenbankstruktur

copyright:
  '&copy; 2023 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/imprint.php">Impressum</a> : <a href="https://legal.stueber.de/privacy.php">Datenschutz</a>'

theme: 
  name: material
  language: de
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections   
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  static_templates:
    - 404.html
  palette:
    - scheme: default
      primary: 'blue'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-7
        name: In den Dunkelmodus wechseln
    - scheme: slate
      primary: 'blue'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-4
        name: In den Hellmodus wechseln
  font: false
  custom_dir: overrides

extra:
  version:
    provider: mike
    
extra_css:
  - assets/css/custom.css

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true
  
markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  
